#!/usr/bin/env node
var fs = require('fs')
var upload = require('./libs/upload')

const findAndUpload = (type) => {
  var crxfile, xpifile = null

  fs.readdirSync('build/' + type).forEach(function (file) {
    if (/xpi$/.test(file)) return xpifile = file
    if (/crx$/.test(file)) return crxfile = file
  })

  if (!crxfile) {
    console.error('It requires crx file')
    process.exit(-1)
  }

  if (!xpifile) {
    console.error('It requires xpi file')
    process.exit(-1)
  }

  var path = `gyazo-chrome-extension/${Date.now()}/`

  upload({targetEnv: `firefox alpha build (${type})`,  fileName: `${type}/${xpifile}`, path})
  upload({targetEnv: `chrome alpha build (${type})`,  fileName: `${type}/${crxfile}`, path})
}

findAndUpload('personal')
findAndUpload('teams')
