#!/usr/bin/env node
var manifest = require('../src/manifest.json')
if (process.env.TARGET === 'firefox') {
  var manifestPath = '../dist/firefox/manifest.json'
} else {
  var manifestPath = '../dist/chrome/manifest.json'
}
var packageVer = require('../package.json').version
manifest.version = packageVer
require('fs').writeFileSync(
  require('path').resolve(__dirname, manifestPath),
  JSON.stringify(manifest, null, 2)
)
